In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.sum(arr)

21

In [4]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [5]:
np.cumsum(arr, axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [6]:
np.cumsum(arr, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [7]:
#불리언 배열에서의 sum
arr2 = np.array([[12,7,20],[21,33,9],[8,21,40]])
arr2

array([[12,  7, 20],
       [21, 33,  9],
       [ 8, 21, 40]])

In [8]:
(arr2>=20).sum()

5

In [12]:
gubun = np.array(['1라인','2라인','3라인','4라인'])
data = np.random.randn(4,4)

In [10]:
gubun

array(['1라인', '2라인', '3라인', '4라인'], dtype='<U3')

In [13]:
data

array([[ 0.81771568, -1.08275838, -0.80047769,  0.42609877],
       [-0.16805187,  0.51679064,  0.5225045 , -0.23258229],
       [ 0.27879099, -0.6087575 , -0.15210576,  0.36409302],
       [-0.95573628, -1.6125173 ,  1.64774868,  1.22402591]])

In [14]:
data[gubun=='2라인',2:]

array([[ 0.5225045 , -0.23258229]])

In [15]:
data[data<0]=0
data

array([[0.81771568, 0.        , 0.        , 0.42609877],
       [0.        , 0.51679064, 0.5225045 , 0.        ],
       [0.27879099, 0.        , 0.        , 0.36409302],
       [0.        , 0.        , 1.64774868, 1.22402591]])

In [17]:
#unique 연산자 이용하여 중복제거하는 작업
a_station = np.array(['송내', '서울역', '용산역', '쳥량리', '송내', '평내', '서울역'])
b_station = np.unique(a_station)
b_station

array(['서울역', '송내', '용산역', '쳥량리', '평내'], dtype='<U3')