In [1]:
import numpy as np

In [2]:
arr2 = np.array([[1,2,3],[2,4,8]])
arr2

array([[1, 2, 3],
       [2, 4, 8]])

In [3]:
arr2.shape

(2, 3)

In [5]:
arr2[1][1]=6
?arr2

In [6]:
arr2.dtype

dtype('int32')

In [7]:
arr3 = arr2.astype(np.float64)
arr3.dtype

dtype('float64')

In [8]:
arr3

array([[1., 2., 3.],
       [2., 6., 8.]])

In [9]:
in_sample=[2.5,2.3,4.8]
arr_sample=np.array(in_sample,dtype="int32")
arr_sample

array([2, 2, 4])

In [11]:
a_1 = np.arange(10)
a_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
in_sample = np.zeros((5,5))
in_sample

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
a_p = np.array([[10,20,30], [30,25,40], [7,9,8]])
a_p

array([[10, 20, 30],
       [30, 25, 40],
       [ 7,  9,  8]])

In [14]:
a_p2 = a_p[:2,:]
a_p2

array([[10, 20, 30],
       [30, 25, 40]])

In [15]:
a_p2[a_p2==30] = 50
a_p2

array([[10, 20, 50],
       [50, 25, 40]])